### ISSUE TITLE
Syntax error: Unexpected token 'export'

### ISSUE THREAD

**Issue by deaglancrew** [stoplightio/json#133]
We're getting some issues in our CI using prism. Looks like it's related to this release ( https://github.com/stoplightio/json/releases/tag/v3.21.1) ?

## Context
It's preventing us from running integration tests atm.

## Current Behavior
On running prism we see: 

```
/home/circleci/.local/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/json/index.js:1
export * from './bundle';
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/circleci/.local/lib/node_modules/@stoplight/prism-cli/node_modules/@stoplight/prism-http/dist/utils/runtimeExpression.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)

Node.js v20.12.1
```

## Expected Behavior

It should run :-)

## Steps to Reproduce
We're using the `cimg/python:3.12.3-node` docker image, installing prism with:

`npm install --prefix=$HOME/.local -g @stoplight/prism-cli`

The error raises when we run prism mock.

## Workarounds

You can manually pin the json version to a working version on install as a temporary workaround:

`npm install --prefix=$HOME/.local -g @stoplight/json@3.21.0 @stoplight/prism-cli`

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4): 
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by silverwind** [comment]
Seeing the same. Imho modules like `spectral-cli` and `prism-cli` should lock their dependencies to exact version to prevent such breakage in the future.

**Comment by dpereverzev** [comment]
+1

**Comment by deaglancrew** [comment]
For anyone here, you can manually pin this dependency when you install, which will get this working, but it's not a very permanent fix.
e.g. 
`npm install --prefix=$HOME/.local -g @stoplight/json@3.21.0 @stoplight/prism-cli` 
in your CI.

@SB-rohitdesai @prafullaAtSB can this be rolled back or fixed easily https://github.com/stoplightio/json/pull/132 ?

**Comment by PratMoha** [comment]
This change is also impacting @stoplight/spectral-cli@v6.11.0 . Seems spectral is referring it to latest @stoplight/json version causing to fail with the above mentioned error.

**Comment by simonbs** [comment]
We're seeing the same when installing the spectral-cli like this:

```bash
npm install -g @stoplight/spectral-cli
```

**Comment by mnaumanali94** [comment]
We are currently working on fixing this!
