### ISSUE TITLE
move general functions over from platform

### ISSUE THREAD

**Issue by marbemac** [stoplightio/json#2]
https://github.com/stoplightio/platform/blob/develop/platform/src/utils/general/index.js

These are helpful generic functions that we should cleanup and preserve.

- Perhaps re-think names along the way.
- Create tests if not already there.
- Add brief description to readme and in comment at top of each function.

- [ ] pruneObject: https://github.com/stoplightio/platform/blob/develop/platform/src/utils/general/index.js#L99
- [ ] sortObjectKeys: https://github.com/stoplightio/platform/blob/develop/platform/src/utils/general/index.js#L124
- [ ] renameObjectKey: https://github.com/stoplightio/platform/blob/develop/platform/src/utils/general/index.js#L146
- [ ] omitByRecursively: https://github.com/stoplightio/platform/blob/develop/platform/src/utils/general/index.js#L174

**Comment by pytlesk4** [comment]
Closing because it's been so long.
